desc DEPARTMENTS;
INSERT into DEPARTMENTS(DEPARTMENT_ID,DEPARTMENT_NAME)
values(72,'PR');

select * from departments

select * from departments

desc EMPLOYEES
INSERT INTO DEPARTMENTS(LOCATION_ID,MANAGER_ID,DEPARTMENT_NAME,DEPARTMENT_ID)
values(1700,200,'RFL',71)

INSERT INTO DEPARTMENTS(LOCATION_ID,MANAGER_ID,DEPARTMENT_NAME,DEPARTMENT_ID)
values(1700,200,'Chapainwbgong',73)
select  * from departments
commit;

